project:
  type: website
  output-dir: _site     # <- lokal bauen wir hierhin (nicht docs)
  resources:
    - images/** 
resource-path:
  - images
  - .

# execute:
#   freeze: false

website:
  title: "your title"
  site-url: https://your-github-name.github.io/your-repo
  repo-url: https://github.com/your-github-name/your-repo
  repo-actions: [] #[source, issue, edit]
  page-navigation: true
  bread-crumbs: false
  open-graph: true
  #favicon:  images/banner.png  
  image: images/banner.png     
  page-footer:
    center: |
      your organisation (<span class="year"></span>) —
      <a class="impressum-link" href="#">Impressum</a>


  
  search:
    location: navbar
    type: textbox

  # comments:
  #   utterances:
  #     repo: your-github-name/your-repo
  #     issue-term: pathname      # Zuordnung pro Seite
  #     label: "comments"         # optional
  #     theme: github-light       # optional

  navbar:
    background: primary   # nutzt Bootstrap "primary" als Navbar-Hintergrund
    foreground: light
    logo: images/your-logo.png
    left:
      - icon: question-square-fill
        text: FAQ
        href: base/faq.qmd
    right:
      - icon: chat-left-text-fill
        text: Interne Lernplattform
        href: https://www.ilias.uni-koeln.de/ilias/login.php?client_id=uk&cmd=force_login&lang=de

  sidebar:
    pinned: true
    align: center
    style: docked
    collapse-level: 1
    contents:
      - section: "Willkommen"
        contents:
          - index.qmd
          - base/about.qmd
      - text: "---"
      - section: "Kurs-Sitzungen"
        contents:
          - section: "Sitzung 1"
            contents:
              - session-1/sitzung-1-01.qmd
          - section: "Sitzung 2"
            contents:
              - session-2/sitzung-2-01.qmd
              - session-2/sitzung-2-02.qmd

format:
  html:
    theme:
      light: [lumen, css/custom.scss]
      # wenn du noch ein eigenes dark-Theme hattest, DEIN Override muss zuletzt kommen:
      dark:  [lumen, css/theme-dark.scss, css/custom.scss]

    css: css/styles.css
    toc: true
    code-copy: true
    code-background: true
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.quarto\.org\/custom'
    md-extensions: +fenced_divs+bracketed_spans+link_attributes  # stabilisiert :::-Blöcke
    include-after-body: ["_footer-year.html"]
lang: de
   
