project:
  type: website
  output-dir: _site     # <- lokal bauen wir hierhin (nicht docs)
  render:
    - index.qmd
    - base/*.qmd
    - session-1/*.qmd
    - session-2/*.qmd
    # - session-3/*.qmd
    # - session-4/*.qmd
    # - session-5/*.qmd
    # - session-6/*.qmd
    # - session-7/*.qmd
    # - session-8/*.qmd
    # - session-9/*.qmd  
# execute:
#   freeze: false

website:
  title: "your title"
  site-url: https://your-github-name.github.io/your-repo
  repo-url: https://github.com/your-github-name/your-repo
  repo-actions: [source, issue, edit]
  page-navigation: true
  bread-crumbs: false
  open-graph: true
  favicon: images/your-logo.png
  image: images/your-logo.png
  page-footer: 'your organisation (202x) [Impressum]({{< href "base/impressum.qmd" >}})'
  
  search:
    location: navbar
    type: textbox

  # comments:
  #   utterances:
  #     repo: your-github-name/your-repo
  #     issue-term: pathname      # Zuordnung pro Seite
  #     label: "comments"         # optional
  #     theme: github-light       # optional

  navbar:
    logo: images/your-logo.png
    left:
      - icon: question-square-fill
        text: FAQ
        href: base/faq.qmd
    right:
      - icon: chat-left-text-fill
        text: Interne Lernplattform
        href: https://ilias.uni-koeln.de/login.php

  sidebar:
    pinned: true
    align: center
    style: docked
    collapse-level: 1
    contents:
      - section: "Willkommen"
        contents:
          - index.qmd
          - base/about.qmd
      - text: "---"
      - section: "Kurs-Sitzungen"
        contents:
          - section: "Sitzung 1"
            contents:
              - session-1/sitzung-1-01.qmd
          - section: "Sitzung 2"
            contents:
              - session-2/sitzung-2-01.qmd
              - session-2/sitzung-2-02.qmd

format:
  html:
    theme:
      light: lumen
      dark: [lumen, css/theme-dark.scss]
    css: css/styles.css
    toc: true
    code-copy: true
    code-background: true
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.quarto\.org\/custom'
    md-extensions: +fenced_divs+bracketed_spans+link_attributes  # stabilisiert :::-Blöcke
lang: de
