name: Quarto build → docs on main

on:
  push:
    branches: [main]
    paths-ignore:
      - "docs/**"              # verhindert Re-Trigger durch Bot-Commit
  workflow_dispatch:

permissions:
  contents: write              # wir committen ins Repo

concurrency:
  group: "quarto-build-docs"
  cancel-in-progress: true

jobs:
  build-commit:
    if: github.actor != 'github-actions[bot]'   # Sicherheitsgurt gegen Loops
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        # with:
        #   version: "1.5.57"   # optional pin

      # Nur HTML bauen (kein LaTeX im CI)
      - name: Render site (HTML only) with CI profile
        run: QUARTO_PROFILE=ci quarto render --to html

      # Debug: zeigt, *warum* docs ggf. ignoriert wird
      - name: Debug ignore rule (optional)
        run: git check-ignore -v docs || echo "docs is not ignored"

      - name: Commit built site into docs/
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # Falls docs/ irgendwo ignoriert ist: trotzdem adden
          git add -A -f docs
          if ! git diff --cached --quiet; then
            git commit -m "build: render site to docs [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
