name: Quarto build → docs on main

on:
  push:
    branches: [main]
    paths-ignore: ["docs/**"]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "quarto-build-docs"
  cancel-in-progress: true

jobs:
  build-commit:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: quarto-dev/quarto-actions/setup@v2

      # Clean docs, CNAME/.nojekyll bewahren
      - name: Clean docs/
        run: |
          mkdir -p docs
          [ -f docs/CNAME ] && cp docs/CNAME /tmp/CNAME || true
          [ -f docs/.nojekyll ] && cp docs/.nojekyll /tmp/.nojekyll || true
          rm -rf docs/*
          [ -f /tmp/CNAME ] && mv /tmp/CNAME docs/CNAME || true
          [ -f /tmp/.nojekyll ] && mv /tmp/.nojekyll docs/.nojekyll || true

      - name: Render (HTML only) with CI profile
        env: { QUARTO_PROFILE: ci }
        run: |
          echo "== Effective CI config =="
          quarto inspect . --profile ci | sed -n '/^project:/,/^[^ ]/p'
          echo "== Render =="
          quarto render . --to html --log-level=DEBUG

      - name: Verify output / diagnose
        run: |
          echo "== List outputs =="
          ls -alh docs || true
          ls -alh _site || true
          if [ -f _site/index.html ] && [ ! -f docs/index.html ]; then
            echo "::warning ::Quarto hat nach _site/ gerendert (Profil ignoriert?) – kopiere nach docs/"
            rsync -a --delete _site/ docs/
          fi
          if [ ! -f docs/index.html ]; then
            echo "::error ::docs/index.html fehlt – Pages würde 404 zeigen."
            exit 1
          fi
          [ -f docs/.nojekyll ] || touch docs/.nojekyll

      - name: Commit built site into docs/
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A -f docs
          if ! git diff --cached --quiet; then
            git commit -m "build: render site to docs [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
