name: Build & Deploy (Quarto)

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "docs/**"     # verhindert Loops, da wir docs nicht committen
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "quarto-pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # version: "1.5.57"   # optional pin

      # Falls du irgendwo PDF-Format aktiviert hast, beschränke sicherheitshalber auf HTML:
      - name: Render site (HTML only)
        run: quarto render --to html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs   # passt zu deinem output-dir

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
