name: Quarto build → docs on main

on:
  push:
    branches: [main]
    paths-ignore:
      - "docs/**"              # verhindert Re-Trigger durch Bot-Commit
  workflow_dispatch:

permissions:
  contents: write              # wir committen ins Repo

concurrency:
  group: "quarto-build-docs"
  cancel-in-progress: true

jobs:
  build-commit:
    if: github.actor != 'github-actions[bot]'   # Sicherheitsgurt gegen Loops
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # --- CLEAN: immer frisches docs/ (CNAME/.nojekyll werden geschont) ---
      - name: Clean docs/
        run: |
          mkdir -p docs
          # preserve CNAME/.nojekyll if present
          [ -f docs/CNAME ] && cp docs/CNAME /tmp/CNAME || true
          [ -f docs/.nojekyll ] && cp docs/.nojekyll /tmp/.nojekyll || true
          rm -rf docs/*
          [ -f /tmp/CNAME ] && mv /tmp/CNAME docs/CNAME || true
          [ -f /tmp/.nojekyll ] && mv /tmp/.nojekyll docs/.nojekyll || true

      # Optional: Quarto-eigenes Clean mit CI-Profil
      - name: Quarto clean (ci profile)
        run: QUARTO_PROFILE=ci quarto clean || true

      # --- RENDER: Projekt explizit rendern (inkl. index.qmd) ---
      - name: Render site (HTML only) with CI profile
        run: |
          QUARTO_PROFILE=ci quarto render . --to html --log-level=DEBUG

      # Debug: sehe, ob index.html entstanden ist
      - name: Inspect output (debug)
        run: |
          ls -alh docs || true
          find docs -maxdepth 1 -name "index.html" -print || true

      # --- COMMIT: baute Site zurück nach main ---
      - name: Commit built site into docs/
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A -f docs
          if ! git diff --cached --quiet; then
            git commit -m "build: render site to docs [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
