name: Quarto Build (HTML + DOCX + PDF)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Quarto + TinyTeX
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: Show versions
        run: |
          quarto --version
          tlmgr --version || true

      # Falls die Hikmah-Extension NICHT im Repo committet ist:
      - name: Ensure hikmah extension (no commit)
        run: |
          if ! quarto list extensions | grep -q 'andrewheiss/hikmah-academic-quarto'; then
            quarto install extension andrewheiss/hikmah-academic-quarto
          fi

      # ── Render separat pro Format ─────────────────────────────────────────────
      - name: Render HTML (profile=ci)
        env: { QUARTO_PROFILE: ci }
        run: |
          quarto render . --to html --log-level=INFO

      - name: Render DOCX (profile=ci)
        env: { QUARTO_PROFILE: ci }
        run: |
          quarto render . --to docx --log-level=INFO

      - name: Render PDF (hikmah-pdf, profile=ci)
        env: { QUARTO_PROFILE: ci }
        run: |
          quarto render . --to hikmah-pdf --log-level=INFO

      # ── Sanity-Check & Commit nur der Website-Ausgabe ───────────────────────
      - name: Check docs has index.html
        run: |
          ls -alh docs || (echo "docs/ missing" && exit 1)
          test -f docs/index.html || (echo "docs/index.html missing" && exit 1)

      - name: Commit & push docs
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -f docs
          git commit -m "CI: render HTML+DOCX+PDF to docs [skip ci]" || echo "Nothing to commit"
          git push
