name: Quarto build → docs on main

on:
  push:
    branches: [main]
    # verhindert Re-Trigger durch den Bot-Commit in docs/
    paths-ignore:
      - "docs/**"
  workflow_dispatch:

permissions:
  contents: write   # wir committen ins Repo

jobs:
  build-commit:
    # zusätzliche Sicherung gegen Endlosschleifen
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        # with:
        #   version: "1.5.57"   # optional pin

      # Wichtig: nur HTML bauen (kein LaTeX/TinyTeX nötig)
      - name: Render site (HTML only)
        run: quarto render --to html

      - name: Commit built site into docs/
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A docs
          if ! git diff --cached --quiet; then
            git commit -m "build: render site to docs [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
