name: Quarto build → docs on main

on:
  push:
    branches: [main]
    paths-ignore:
      - "docs/**"              # verhindert, dass der Bot-Commit in docs/ den Job erneut triggert
  workflow_dispatch:

permissions:
  contents: write              # wir committen die gebaute Site zurück auf main

concurrency:
  group: "quarto-build-docs"
  cancel-in-progress: true

jobs:
  build-commit:
    if: github.actor != 'github-actions[bot]'   # Sicherheitsgurt gegen Loops
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        # with:
        #   version: "1.5.57"   # optional pin

      # Clean: docs/ leeren, CNAME/.nojekyll behalten
      - name: Clean docs/
        run: |
          mkdir -p docs
          [ -f docs/CNAME ] && cp docs/CNAME /tmp/CNAME || true
          [ -f docs/.nojekyll ] && cp docs/.nojekyll /tmp/.nojekyll || true
          rm -rf docs/*
          [ -f /tmp/CNAME ] && mv /tmp/CNAME docs/CNAME || true
          [ -f /tmp/.nojekyll ] && mv /tmp/.nojekyll docs/.nojekyll || true

      # Render: Projekt mit CI-Profil bauen (schreibt nach docs/)
      - name: Render project (HTML only) with CI profile
        env:
          QUARTO_PROFILE: ci
        run: |
          echo "== Effective CI config =="
          quarto inspect . --profile ci | sed -n '/^project:/,/^[^ ]/p'
          echo "== Render =="
          quarto render . --to html --log-level=DEBUG

      # Verify: index.html muss existieren, sonst Fehler (vermeidet 404)
      - name: Verify output
        run: |
          ls -alh docs || true
          if [ ! -f docs/index.html ]; then
            echo "::error ::docs/index.html fehlt – Pages würde 404 zeigen."
            exit 1
          fi
          [ -f docs/.nojekyll ] || touch docs/.nojekyll

      # Commit: gebaute Site in docs/ zurück auf main
      - name: Commit built site into docs/
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A -f docs
          if ! git diff --cached --quiet; then
            git commit -m "build: render site to docs [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
