name: Quarto build → docs on main

on:
  push:
    branches: [main]
    paths-ignore: ["docs/**"]   # verhindert Re-Trigger durch Bot-Commit
  workflow_dispatch:

permissions:
  contents: write                # wir committen ins Repo

jobs:
  build-commit:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: quarto-dev/quarto-actions/setup@v2

      - name: Render site (HTML only) with CI profile
        run: QUARTO_PROFILE=ci quarto render --to html

      - name: Commit built site into docs/
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A docs
          if ! git diff --cached --quiet; then
            git commit -m "build: render site to docs [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
